development:
  adapter: postgresql
  database: wedding_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wedding_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wedding_production
  host: localhost
  pool: 5
  timeout: 5000
